Restaurant/Controllers/MenuCategoryController.cs
using Applications.MenuCategory_servic;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace Restaurant.Controllers
{
    public class MenuCategoryController : Controller
    {
        private readonly IMenuCategoryservis menuCategoryservis;
        public MenuCategoryController(IMenuCategoryservis menuCategoryservis)
        {
            this.menuCategoryservis = menuCategoryservis;
        }

        public async Task<IActionResult> Getall()
        {
            var result = await menuCategoryservis.GetAll();
            return View(result);
        }


        [HttpGet]
        public async Task<IActionResult> New()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> New(MenuCategory menuCategory)
        {
            if (ModelState.IsValid)
            {
                await menuCategoryservis.Create(menuCategory);
                return RedirectToAction("Getall");
            }
            return View(menuCategory);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await menuCategoryservis.GetById(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(MenuCategory menuCategory)
        {
            if (ModelState.IsValid)
            {
                await menuCategoryservis.Update(menuCategory);

                return RedirectToAction("GetAll");
            }
            return View(menuCategory);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await menuCategoryservis.GetById(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await menuCategoryservis.Delete(id);
            return RedirectToAction("GetAll");
        }


        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> IsCategoryNameInUse(string name,int id)
        {

            var existingCategory = await menuCategoryservis.GetById(id);
            if (existingCategory != null && existingCategory.Name == name)
            {
                return Json(true);
            }

            var categoryExists = await menuCategoryservis.GetByName1(name);
            if (categoryExists)
            {
                return Json($"Category name {name} is already in use.");
            }
            return Json(true);

        }

    }
}

Restaurant/Controllers/MenuItemController.cs
using Applications.MenuCategory_servic;
using Applications.MenuItem_servic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Configuration.UserSecrets;
using Models;

namespace Restaurant.Controllers
{
    public class MenuItemController : Controller
    {
        private readonly IMenuItem MenuItemserves;
        private readonly IMenuCategoryservis menuCategoryservis;
        public MenuItemController(IMenuItem menuItem, IMenuCategoryservis menu)
        {
            MenuItemserves = menuItem;
            menuCategoryservis = menu;
        }
        public async Task<IActionResult> Getall()
        {
            ViewBag.Categories = await menuCategoryservis.GetAll();
            var result = await MenuItemserves.GetAll();
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> New()
        {
            ViewBag.Categories = await menuCategoryservis.GetAll();
            return View();
        }
        [HttpPost]
        [HttpPost]
        public async Task<IActionResult> New(MenuItem item)
        {
            ViewBag.Category = new SelectList(await menuCategoryservis.GetAll(), "Id", "Name");

            if (ModelState.IsValid)
            {
                if (item.ImageFile != null && item.ImageFile.Length > 0)
                {
                    var uploadDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");
                    if (!Directory.Exists(uploadDir))
                        Directory.CreateDirectory(uploadDir);

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(item.ImageFile.FileName);
                    var filePath = Path.Combine(uploadDir, fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await item.ImageFile.CopyToAsync(stream);
                    }

                    item.ImageUrl =  fileName;
                }

                await MenuItemserves.Create(item);
                return RedirectToAction("GetAll");
            }

            return View(item);
        }

        private void useing(MemoryStream memoryStream, object value)
        {
            throw new NotImplementedException();
        }

        private void useing(object var, object value)
        {
            throw new NotImplementedException();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Categories = await menuCategoryservis.GetAll();
            var result = await MenuItemserves.GetById(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        [HttpPost]
        public async Task<IActionResult> Edit(MenuItem item)
        {
            ViewBag.Categories = new SelectList(await menuCategoryservis.GetAll(), "Id", "Name");

            if (ModelState.IsValid)
            {
                var existingItem = await MenuItemserves.GetById(item.Id);
                if (existingItem == null)
                    return NotFound();

               
                existingItem.Name = item.Name;
                existingItem.Description = item.Description;
                existingItem.Price = item.Price;
                existingItem.quanty = item.quanty;
                existingItem.PreparationTimeMinutes = item.PreparationTimeMinutes;
                existingItem.CategoryId = item.CategoryId;

                if (item.ImageFile != null && item.ImageFile.Length > 0)
                {
                    var uploadDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");

                    if (!Directory.Exists(uploadDir))
                        Directory.CreateDirectory(uploadDir);

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(item.ImageFile.FileName);
                    var filePath = Path.Combine(uploadDir, fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await item.ImageFile.CopyToAsync(stream);
                    }

                    if (!string.IsNullOrEmpty(existingItem.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", existingItem.ImageUrl.TrimStart('/'));
                        if (System.IO.File.Exists(oldImagePath))
                            System.IO.File.Delete(oldImagePath);
                    }

                    existingItem.ImageUrl =   fileName;
                }

                await MenuItemserves.Update(existingItem);
                return RedirectToAction("Getall");
            }

            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await MenuItemserves.GetById(id);
            ViewBag.Categories = await menuCategoryservis.GetAll();
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await MenuItemserves.Delete(id);
            return RedirectToAction("GetAll");
        }

       

        
        public async Task<IActionResult> Details(int id)
        {
            ViewBag.categories = await menuCategoryservis.GetAll();
            var result = await MenuItemserves.GetById(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> IsMenuItemNameInUse(string name, int id)
        {

            var existingMenuItem = await MenuItemserves.GetById(id);
            if (existingMenuItem != null && existingMenuItem.Name == name)
            {
                return Json(true);
            }

            var existingMenuItem1 = await MenuItemserves.GetByName(name);
            if (existingMenuItem1!=null)
            {
                return Json($"MenuItem name {name} is already in use.");
            }

            return Json(true);

        }

    }
}

Restaurant/Controllers/OrderController.cs
using Applications.Dtos;
using Applications.MenuCategory_servic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models;
using System.Security.Claims;

namespace Restaurant.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderServes _orderService;

        public OrderController(IOrderServes orderService)
        {
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Order> orders;
        


            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

           
            if (User.IsInRole("Admin"))
            {
              
                orders = await _orderService.GetAllOrdersAsync();
                ViewBag.IsAdminView = true;


                var now = DateTime.Now;
                var monthlyRevenue = orders
                    .Where(o => o.OrderDate.Month == now.Month && o.OrderDate.Year == now.Year)
                    .Sum(o => o.TotalAmount);

                ViewBag.MonthlyRevenue = monthlyRevenue;

            }
            else
            {

                var allOrders = await _orderService.GetAllOrdersAsync();
                orders = allOrders
                    .Where(o => o.userId == userId)
                    .OrderByDescending(o => o.OrderDate)
                    .ToList();

                ViewBag.IsAdminView = false;
                var now = DateTime.Now;
                var userMonthlyRevenue = orders
                    .Where(o => o.OrderDate.Month == now.Month && o.OrderDate.Year == now.Year)
                    .Sum(o => o.TotalAmount);

                ViewBag.UserMonthlyRevenue = userMonthlyRevenue;


            }

            return View(orders);
        }
      
        public async Task<IActionResult> Create()
        {
            var menuItems = await _orderService.GetAvailableMenuItemsAsync();
            ViewBag.MenuItems = menuItems;
            


            var currentHour = DateTime.Now.Hour;
            if (currentHour >= 15 && currentHour < 17)
            {
                ViewBag.HappyHourMessage = "Happy Hour! Get 20% off your order (3 PM - 5 PM)";
            }

            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApplicationUser user, Order order, int[] menuItemIds, int[]? quantities)
        {
            if (menuItemIds == null || menuItemIds.Length == 0)
            {
                ModelState.AddModelError("", "Please select at least one menu item.");
            }

            if (quantities == null || quantities.Length == 0)
            {
                ModelState.AddModelError("", "Quantity information is missing or invalid.");
            }

          
            if (order.OrderType == OrderType.Delivery && string.IsNullOrWhiteSpace(order.DeliveryAddress))
            {
                ModelState.AddModelError("DeliveryAddress", "Delivery address is required for delivery orders.");
            }

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            user.Id = userId;
            order.userId = user.Id;
                
            ModelState.Remove("user");
            ModelState.Remove("userId");
            ModelState.Remove("OrderItems");

            if (ModelState.IsValid)
            {
                try
                {
                    await _orderService.CreateOrderAsync(order, menuItemIds, quantities);
                    TempData["Success"] = "Order created successfully!";
                    TempData["OrderId"] = order.Id;
                    return RedirectToAction(nameof(Details), new { id = order.Id });
                }
                catch (ArgumentException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (InvalidOperationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"An error occurred while creating the order: {ex.Message}");
                }
            }
            

            ViewBag.MenuItems = await _orderService.GetAvailableMenuItemsAsync();

            var currentHour = DateTime.Now.Hour;
            if (currentHour >= 15 && currentHour < 17)
            {
                ViewBag.HappyHourMessage = "Happy Hour! Get 20% off your order (3 PM - 5 PM)";
            }

            return View(order);
        }

        
        public async Task<IActionResult> Details(int id)
        {
            var order = await _orderService.GetOrderDetailsAsync(id);
            if (order == null)
                return NotFound();

          
            var availableStatuses = await _orderService.GetAvailableStatusTransitionsAsync(id);
            ViewBag.AvailableStatuses = availableStatuses;

           
            var canUpdate = await _orderService.CanUpdateOrderStatusAsync(id);
            ViewBag.CanUpdateStatus = canUpdate;

            
            var canCancel = await _orderService.CanCancelOrderAsync(id);
            ViewBag.CanCancel = canCancel;

           
            switch (order.OrderStatus)
            {
                case OrderStatus.Pending:
                    ViewBag.StatusMessage = "Your order is pending. It will start preparing in a few minutes.";
                    ViewBag.StatusClass = "info";
                    break;
                case OrderStatus.Preparing:
                    ViewBag.StatusMessage = "Your order is being prepared. Hang tight!";
                    ViewBag.StatusClass = "warning";
                    break;
                case OrderStatus.Ready:
                    ViewBag.StatusMessage = "Your order is ready for pickup/delivery!";
                    ViewBag.StatusClass = "success";
                    break;
                case OrderStatus.Delivered:
                    ViewBag.StatusMessage = "Your order has been delivered. Enjoy your meal!";
                    ViewBag.StatusClass = "success";
                    break;
                case OrderStatus.Cancelled:
                    ViewBag.StatusMessage = "This order has been cancelled.";
                    ViewBag.StatusClass = "danger";
                    break;
            }

            return View(order);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateStatus(int id, OrderStatus newStatus)
        {
            var canUpdate = await _orderService.CanUpdateOrderStatusAsync(id);
            if (!canUpdate)
            {
                TempData["Error"] = "Cannot update status for this order (already Ready, Delivered, or Cancelled).";
                return RedirectToAction(nameof(Details), new { id });
            }

            var result = await _orderService.UpdateOrderStatusAsync(id, newStatus);
            if (result)
            {
                TempData["Success"] = $"Order status updated to {newStatus} successfully!";
            }
            else
            {
                TempData["Error"] = "Failed to update order status. Invalid status transition.";
            }

            return RedirectToAction(nameof(Details), new { id });
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cancel(int id)
        {
            var canCancel = await _orderService.CanCancelOrderAsync(id);
            if (!canCancel)
            {
                TempData["Error"] = "Cannot cancel this order. Orders that are Ready or Delivered cannot be cancelled.";
                return RedirectToAction(nameof(Details), new { id });
            }

            var result = await _orderService.CancelOrderAsync(id);
            if (result)
            {
                TempData["Success"] = "Order cancelled successfully!";
            }
            else
            {
                TempData["Error"] = "Failed to cancel order.";
            }

            return RedirectToAction(nameof(Details), new { id });
        }
    }
}

Restaurant/Views/Shared/_Layout.cshtml
@* <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Restaurant.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Restaurant</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MenuCategory" asp-action="Getall">Category</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MenuItem" asp-action="Getall">MenuItem</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Restaurant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
 *@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Restaurant.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary-color: #d4a574;
            --secondary-color: #2c3e50;
            --accent-color: #e67e22;
            --dark-bg: #1a1a1a;
            --light-bg: #f8f9fa;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Poppins', sans-serif;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        /* Navbar Styling */
        .navbar {
            background: linear-gradient(135deg, var(--dark-bg) 0%, var(--secondary-color) 100%) !important;
            padding: 1.2rem 0;
            box-shadow: 0 4px 20px rgba(0,0,0,0.15);
            border: none !important;
        }

        .navbar-brand {
            font-family: 'Playfair Display', serif;
            font-size: 1.8rem;
            font-weight: 700;
            color: var(--primary-color) !important;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
            transition: all 0.3s ease;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .navbar-brand::before {
            content: "🍽️";
            font-size: 1.5rem;
        }

        .navbar-brand:hover {
            transform: scale(1.05);
            color: #fff !important;
        }

        .nav-link {
            color: rgba(255,255,255,0.9) !important;
            font-weight: 500;
            font-size: 1rem;
            margin: 0 5px;
            padding: 10px 20px !important;
            border-radius: 25px;
            transition: all 0.3s ease;
            position: relative;
        }

        .nav-link:hover {
            background: var(--primary-color);
            transform: translateY(-2px);
            box-shadow: 0 4px 15px rgba(212, 165, 116, 0.4);
            color: white !important;
        }

        .nav-link.active {
            background: var(--accent-color);
            color: white !important;
        }

        /* Container */
        .container-fluid {
            max-width: 1400px;
        }

        /* Main Content */
        main {
            background: white;
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.1);
            margin-bottom: 40px;
            animation: fadeIn 0.8s ease;
            min-height: 400px;
        }

        /* Footer */
        .footer {
            background: linear-gradient(135deg, var(--dark-bg) 0%, var(--secondary-color) 100%);
            color: white;
            padding: 30px 0;
            margin-top: auto;
            border-radius: 50px 50px 0 0;
            box-shadow: 0 -5px 20px rgba(0,0,0,0.1);
            border: none !important;
        }

        .footer a {
            color: var(--primary-color);
            text-decoration: none;
            transition: all 0.3s ease;
            font-weight: 500;
        }

        .footer a:hover {
            color: var(--accent-color);
            text-decoration: none;
        }

       
        /* Navbar Toggler */
        .navbar-toggler {
            background: var(--primary-color);
            border: none;
            padding: 8px 12px;
        }

        .navbar-toggler:focus {
            box-shadow: 0 0 0 0.2rem rgba(212, 165, 116, 0.5);
        }

        .navbar-toggler-icon {
            background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba(255, 255, 255, 1)' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
        }

        /* Responsive */
       

            main {
                padding: 20px;
            }

            .nav-link {
                margin: 5px 0;
            }
        }

        /* Custom Box Shadow */
        .box-shadow {
            box-shadow: 0 4px 20px rgba(0,0,0,0.15) !important;
        }

        /* Smooth transitions */
        * {
            transition: background-color 0.3s ease, color 0.3s ease;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ghazaly Restaurant</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MenuCategory" asp-action="Getall">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MenuItem" asp-action="Getall">MenuItem</a>
                        </li>
      



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                        </li>



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">SignOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Restaurant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>